Bump activerecord from 7.2.1.2 to 7.2.2 (#127)
Bumps [activerecord](https://github.com/rails/rails) from 7.2.1.2 to
7.2.2.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/rails/rails/releases">activerecord's
releases</a>.</em></p>
<blockquote>
<h2>7.2.2</h2>
<h2>Active Support</h2>
<ul>
<li>
<p>Include options when instrumenting
<code>ActiveSupport::Cache::Store#delete</code> and
<code>ActiveSupport::Cache::Store#delete_multi</code>.</p>
<p><em>Adam Renberg Tamm</em></p>
</li>
<li>
<p>Print test names when running <code>rails test -v</code> for parallel
tests.</p>
<p><em>John Hawthorn</em>, <em>Abeid Ahmed</em></p>
</li>
</ul>
<h2>Active Model</h2>
<ul>
<li>
<p>Fix regression in <code>alias_attribute</code> to work with user
defined methods.</p>
<p><code>alias_attribute</code> would wrongly assume the attribute
accessor was generated by Active Model.</p>
<pre lang="ruby"><code>class Person
  include ActiveModel::AttributeMethods
<p>define_attribute_methods :name
attr_accessor :name</p>
<p>alias_attribute :full_name, :name
end</p>
<p>person.full_name # =&gt; NoMethodError: undefined method `attribute'
for an instance of Person
</code></pre></p>
<p><em>Jean Boussier</em></p>
</li>
</ul>
<h2>Active Record</h2>
<ul>
<li>
<p>Fix support for <code>query_cache: false</code> in
<code>database.yml</code>.</p>
<p><code>query_cache: false</code> would no longer entirely disable the
Active Record query cache.</p>
<p><em>zzak</em></p>
</li>
<li>
<p>Set <code>.attributes_for_inspect</code> to <code>:all</code> by
default.</p>
<p>For new applications it is set to <code>[:id]</code> in
config/environment/production.rb.</p>
<p>In the console all the attributes are always shown.</p>
<p><em>Andrew Novoselac</em></p>
</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/rails/rails/blob/v7.2.2/activerecord/CHANGELOG.md">activerecord's
changelog</a>.</em></p>
<blockquote>
<h2>Rails 7.2.2 (October 30, 2024)</h2>
<ul>
<li>
<p>Fix support for <code>query_cache: false</code> in
<code>database.yml</code>.</p>
<p><code>query_cache: false</code> would no longer entirely disable the
Active Record query cache.</p>
<p><em>zzak</em></p>
</li>
<li>
<p>Set <code>.attributes_for_inspect</code> to <code>:all</code> by
default.</p>
<p>For new applications it is set to <code>[:id]</code> in
config/environment/production.rb.</p>
<p>In the console all the attributes are always shown.</p>
<p><em>Andrew Novoselac</em></p>
</li>
<li>
<p><code>PG::UnableToSend: no connection to the server</code> is now
retryable as a connection-related exception</p>
<p><em>Kazuma Watanabe</em></p>
</li>
<li>
<p>Fix marshalling of unsaved associated records in 7.1 format.</p>
<p>The 7.1 format would only marshal associated records if the
association was loaded.
But associations that would only contain unsaved records would be
skipped.</p>
<p><em>Jean Boussier</em></p>
</li>
<li>
<p>Fix incorrect SQL query when passing an empty hash to
<code>ActiveRecord::Base.insert</code>.</p>
<p><em>David Stosik</em></p>
</li>
<li>
<p>Allow to save records with polymorphic join tables that have
<code>inverse_of</code>
specified.</p>
<p><em>Markus Doits</em></p>
</li>
<li>
<p>Fix association scopes applying on the incorrect join when using a
polymorphic <code>has_many through:</code>.</p>
<p><em>Joshua Young</em></p>
</li>
<li>
<p>Fix <code>dependent: :destroy</code> for bi-directional has one
through association.</p>
<p>Fixes <a
href="https://redirect.github.com/rails/rails/issues/50948">#50948</a>.</p>
<pre lang="ruby"><code>class Left &lt; ActiveRecord::Base
  has_one :middle, dependent: :destroy
  has_one :right, through: :middle
end
<p></code></pre></p>
</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/rails/rails/commit/d0dcb8fa6073a0c4d42600c15e82e3bb386b27d3"><code>d0dcb8f</code></a>
Preparing for 7.2.2 release</li>
<li><a
href="https://github.com/rails/rails/commit/f6916e7d863cb53f8738265f4b5b4629990e84f0"><code>f6916e7</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/53494">#53494</a>
from zzak/re-53492</li>
<li><a
href="https://github.com/rails/rails/commit/a7858b54505698d40e12cba56e3c2702ebdadfd8"><code>a7858b5</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/53472">#53472</a>
from p8/activerecord/improve-attributes-for-inspect...</li>
<li><a
href="https://github.com/rails/rails/commit/e6a8acd749f0824cbd180014482f3d2dd4bf976c"><code>e6a8acd</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/53475">#53475</a>
from p8/activerecord/show-all-attributes-in-console</li>
<li><a
href="https://github.com/rails/rails/commit/91aac4a9348fcf6568a9a2a724c587f524d940b1"><code>91aac4a</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/53484">#53484</a>
from zzak/query_cache-config-disable</li>
<li><a
href="https://github.com/rails/rails/commit/e1cccdcb155f17623118ca1df11065323c2c63c0"><code>e1cccdc</code></a>
Add CHANGELOG entry for 170e6c178b7358a87a7304bdf80273e0b153f6fd</li>
<li><a
href="https://github.com/rails/rails/commit/897b382d80743fc30e62b1edec1e39dbe1e7305e"><code>897b382</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/53400">#53400</a>
from wata727/translate_no_connection_to_not_establi...</li>
<li><a
href="https://github.com/rails/rails/commit/c5292519cc724a882b9344759a0ec1e121c30ffe"><code>c529251</code></a>
Revert &quot;Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/53398">#53398</a>
from kamipo/fix_strict_loading_propagation&quot;</li>
<li><a
href="https://github.com/rails/rails/commit/2975a880b6568207b2b3bbd8b6bf644e04b29bb5"><code>2975a88</code></a>
Merge remote-tracking branch 'origin/7-2-sec' into 7-2-stable</li>
<li><a
href="https://github.com/rails/rails/commit/500e2a9bb5ff1c9bf830b27cb07541644bc8093f"><code>500e2a9</code></a>
Fix API doc for <code>has_many</code> [ci-skip]</li>
<li>Additional commits viewable in <a
href="https://github.com/rails/rails/compare/v7.2.1.2...v7.2.2">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=activerecord&package-manager=bundler&previous-version=7.2.1.2&new-version=7.2.2)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>